# Generated by Django 3.0.4 on 2020-06-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_api', '0002_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
